'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { ChatHeader } from '@/components/layout/chat-header'
import { ChatMessages } from './chat-messages'
import { ChatInput } from './chat-input'
import { ComplianceCanvas } from './compliance-canvas'
import { RAGProgress } from './rag-progress'
import { TypingIndicator, EnhancedLoading } from './loading-indicator'
import { useChatModeStore } from '@/lib/store/chat-mode-store'
import { useRAGStore } from '@/lib/store/rag-store'
import { useAuthStore } from '@/lib/store/auth-store'
import { useChatStore } from '@/lib/store/chat-store'
import { useFileUploadStore } from '@/lib/store/file-upload-store'
import { useSidebarStore } from '@/lib/store/sidebar-store'
import type { Message } from '@/types'
import { AlertCircle, FileText } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { DragDropOverlay } from './drag-drop-overlay'
import { UploadedFilesList } from './uploaded-files-list'
import { showToast } from '@/components/ui/toast'
import { EmptyState } from './empty-state'
import { CenteredInput } from './centered-input'

interface ChatContainerProps {
  messages: Message[]
}

// Generate mock compliance report based on file
function generateMockComplianceReport(fileName: string, query: string): string {
  const timestamp = new Date().toLocaleDateString('en-PH', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
  
  // Different reports based on file name patterns
  if (fileName.toLowerCase().includes('disaster') || fileName.toLowerCase().includes('barangay') || fileName.toLowerCase().includes('plan')) {
    return `# Compliance Analysis Report

## ⚠️ AI-Generated Analysis Disclaimer
**This analysis is generated by AI and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified legal professionals, compliance officers, or government authorities. Always verify compliance requirements with official sources and seek professional legal counsel for critical decisions.**

---

**Document:** ${fileName}  
**Analysis Date:** ${timestamp}  
**Query:** ${query}

## Compliance Score: 75% ⚠️

### Overall Assessment
Your barangay disaster preparedness plan shows good foundational elements but requires several critical additions to fully comply with **RA 10121 (Philippine Disaster Risk Reduction and Management Act of 2010)** and related NDRRMC guidelines.

---

## ✅ Compliant Sections

### 1. Evacuation Plan (Section 3)
- **Status:** ✅ Compliant
- **Finding:** Evacuation centers, routes, and procedures are clearly documented
- **Reference:** RA 10121, Section 12 - Local DRRM Plans

### 2. BDRRMC Structure (Section 4.1)
- **Status:** ✅ Compliant  
- **Finding:** Committee structure follows NDRRMC guidelines with proper designation of roles
- **Reference:** NDRRMC Memorandum Circular No. 4, Series of 2012

### 3. Relief Operations (Section 5)
- **Status:** ✅ Compliant
- **Finding:** Relief goods inventory and distribution plan documented
- **Reference:** RA 10121, Section 13 - Relief and Recovery

---

## ⚠️ Sections Needing Minor Revisions

### 1. Communication System (Section 7)
- **Issue:** Missing social media monitoring and fake news protocols
- **Recommendation:** Add procedures for verifying and countering misinformation during disasters
- **Reference:** NDRRMC Guidelines on Information Management

### 2. Budget Allocation (Section 8)
- **Issue:** No breakdown for Quick Response Fund (QRF) as mandated
- **Recommendation:** Allocate at least 30% of total DRRM budget to QRF
- **Reference:** RA 10121, Section 21 - Local DRRM Fund

---

## 🚫 Critical Missing Sections

### 1. Risk Assessment and Hazard Mapping
- **Status:** 🚫 Missing
- **Requirement:** Detailed hazard maps showing flood-prone areas, fault lines, and fire-risk zones
- **Impact:** Cannot effectively plan evacuation routes without proper risk assessment
- **Action Required:** Conduct barangay-level hazard mapping with PHIVOLCS and PAGASA data
- **Reference:** RA 10121, Section 12(b) - Risk Assessment

### 2. Community Training Plan
- **Status:** 🚫 Missing  
- **Requirement:** Scheduled training programs for residents on disaster preparedness
- **Impact:** Community may not know proper response procedures during actual disasters
- **Action Required:** 
  - Quarterly community disaster awareness seminars
  - Annual earthquake and fire drills with community participation
  - First aid training for at least 10% of households
- **Reference:** NDRRMC Memorandum Circular No. 5, Series of 2013

### 3. Risk Communication Strategy
- **Status:** 🚫 Missing
- **Requirement:** Clear protocols for warning dissemination and public information
- **Impact:** Delayed or unclear warnings can lead to casualties
- **Action Required:**
  - Multi-channel warning system (sirens, SMS, social media, radio)
  - Pre-scripted emergency messages in Filipino and English
  - Designated information officers
- **Reference:** RA 10121, Section 11 - Information Dissemination

### 4. Post-Disaster Recovery Plan
- **Status:** 🚫 Missing
- **Requirement:** Plans for rehabilitation and reconstruction after disasters
- **Impact:** Slow recovery and potential for recurring vulnerabilities
- **Action Required:**
  - Livelihood restoration programs
  - Psychosocial support services
  - Build-back-better guidelines
- **Reference:** RA 10121, Section 13 - Recovery and Rehabilitation

### 5. Vulnerable Groups Protection
- **Status:** 🚫 Partially Addressed
- **Requirement:** Specific protocols for PWD, elderly, pregnant women, children, and indigenous peoples
- **Impact:** Vulnerable groups may be overlooked during evacuation and relief
- **Action Required:**
  - Database of vulnerable individuals per purok
  - Buddy system for PWD and elderly
  - Special relief packs for infants and medical needs
- **Reference:** RA 10121, Section 16 - Vulnerable and Marginalized Groups

---

## 📋 Recommended Next Steps

### Immediate (Within 1 Month)
1. ✏️ Add Risk Assessment and Hazard Mapping section
2. ✏️ Develop Community Training Plan with schedule
3. ✏️ Create Risk Communication Strategy
4. ✏️ Update Budget to include QRF breakdown

### Short-term (Within 3 Months)
1. 📅 Conduct barangay-wide hazard mapping exercise
2. 📅 Schedule first community disaster preparedness seminar
3. 📅 Establish vulnerable groups database
4. 📅 Conduct table-top exercise with BDRRMC

### Long-term (Within 6 Months)
1. 🎯 Complete Post-Disaster Recovery Plan
2. 🎯 Conduct full-scale disaster drill with community
3. 🎯 Establish partnerships with NGOs for disaster response
4. 🎯 Submit updated plan to City DRRM Office for validation

---

## 📚 Key Legal References

1. **Republic Act No. 10121** - Philippine Disaster Risk Reduction and Management Act of 2010
2. **NDRRMC Memorandum Circular No. 4, Series of 2012** - Guidelines on the Establishment of BDRRMC
3. **NDRRMC Memorandum Circular No. 5, Series of 2013** - Minimum Standards for Community-Based DRRM
4. **RA 10121 IRR** - Implementing Rules and Regulations

---

## ⚖️ Legal Disclaimer

**This AI-generated analysis is provided for informational and educational purposes only. It is not a substitute for:**
- Professional legal advice from licensed attorneys
- Official compliance audits by government agencies
- Consultation with certified disaster risk reduction experts
- Formal validation by the City/Municipal DRRM Office

**Users are strongly advised to:**
- Verify all findings with official government sources
- Consult with legal counsel before making compliance decisions
- Submit plans to proper authorities for official review
- Seek guidance from NDRRMC, OCD, or local DRRM offices

**Limitation of Liability:** The creators and operators of this AI tool assume no liability for decisions made based on this analysis. Users bear full responsibility for ensuring compliance with all applicable laws and regulations.

---

*Generated by LexInsight AI Compliance Assistant*  
*This is an automated analysis. Human review recommended.*`
  }
  
  // Default compliance report for other documents
  return `# Compliance Analysis Report

## ⚠️ AI-Generated Analysis Disclaimer
**This analysis is generated by AI and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified legal professionals, compliance officers, or government authorities. Always verify compliance requirements with official sources and seek professional legal counsel for critical decisions.**

---

**Document:** ${fileName}  
**Analysis Date:** ${timestamp}  
**Query:** ${query}

## Compliance Score: Analyzing...

### Document Processing
Your document is being analyzed for compliance with relevant Philippine laws and regulations. This may take a few moments.

### What We're Checking:
- Applicable laws and regulations
- Required sections and documentation
- Compliance gaps and risks
- Recommendations for improvement

---

## ⚖️ Legal Disclaimer

**This AI-generated analysis is provided for informational and educational purposes only. It is not a substitute for:**
- Professional legal advice from licensed attorneys
- Official compliance audits by government agencies  
- Consultation with certified compliance experts
- Formal validation by relevant government offices

**Users are strongly advised to:**
- Verify all findings with official government sources
- Consult with legal counsel before making compliance decisions
- Submit documents to proper authorities for official review
- Seek guidance from relevant regulatory agencies

---

*Generated by LexInsight AI Compliance Assistant*  
*This is an automated analysis. Human review recommended.*`
}

export function ChatContainer({ messages: initialMessages }: ChatContainerProps) {
  const { mode } = useChatModeStore()
  const { user } = useAuthStore()
  const { 
    currentResponse, 
    loading, 
    error, 
    wsEvents, 
    submitQuery, 
    clearError 
  } = useRAGStore()
  const { activeChat, messages: chatMessages, fetchMessages, loadingMessages } = useChatStore()
  const { addFiles, uploadedFiles, canAddMore } = useFileUploadStore()
  
  const [showCanvas, setShowCanvas] = useState(false)
  const [canvasContent, setCanvasContent] = useState('')
  const [canvasFileName, setCanvasFileName] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)
  const [deepSearchResult, setDeepSearchResult] = useState<any>(null)
  const [currentQuery, setCurrentQuery] = useState<string>('')
  const [isTransitioning, setIsTransitioning] = useState(false)

  // Handle file drop - only add to list, don't process yet
  const handleFileDrop = (files: File[]) => {
    if (!canAddMore()) {
      showToast('Maximum 3 documents allowed', 'error')
      return
    }

    // Validate file sizes (5MB limit)
    const maxSize = 5 * 1024 * 1024 // 5MB in bytes
    const oversizedFiles = files.filter(file => file.size > maxSize)
    
    if (oversizedFiles.length > 0) {
      showToast(`Some files exceed 5MB limit and were not added`, 'error')
    }

    const validFiles = files.filter(file => file.size <= maxSize)
    
    if (validFiles.length > 0) {
      addFiles(validFiles)
      showToast(`${validFiles.length} document(s) added. Click send to analyze.`, 'success')
    }
  }

  // Get messages for active chat
  const messages = activeChat ? (chatMessages[activeChat.id] || []) : initialMessages
  const hasMessages = messages.length > 0

  // Fetch messages when active chat changes
  useEffect(() => {
    if (activeChat && !chatMessages[activeChat.id]) {
      fetchMessages(activeChat.id)
    }
  }, [activeChat, chatMessages, fetchMessages])

  // Handle prompt selection from empty state
  const handlePromptSelect = (prompt: string) => {
    // Dispatch event to notify container
    const event = new CustomEvent('query-submitted', {
      detail: { query: prompt }
    })
    window.dispatchEvent(event)
    
    submitQuery(prompt, user?.id)
  }

  // Handle centered input send
  const handleCenteredSend = (message: string) => {
    // Start transition animation
    setIsTransitioning(true)
    
    // Close sidebar on send (always, not just mobile)
    const sidebarStore = useSidebarStore.getState()
    sidebarStore.close()
    
    // Dispatch event to notify container
    const event = new CustomEvent('query-submitted', {
      detail: { query: message }
    })
    window.dispatchEvent(event)
    
    submitQuery(message, user?.id)
    
    // Reset transition after animation
    setTimeout(() => setIsTransitioning(false), 300)
  }

  // Show canvas when we have a RAG response in compliance mode
  useEffect(() => {
    if (mode === 'compliance' && currentResponse) {
      setShowCanvas(true)
      setCanvasContent(currentResponse.summary)
      setCanvasFileName('rag-analysis')
    } else if (mode !== 'compliance') {
      setShowCanvas(false)
      setCanvasContent('')
      setCanvasFileName('')
    }
  }, [mode, currentResponse])

  // Add RAG responses to messages in general mode
  // Note: This is handled by the chat store now, but keeping for backward compatibility
  useEffect(() => {
    if (currentResponse && mode === 'general' && currentQuery) {
      // Messages are now managed by the store
      // This effect is kept for any additional UI updates needed
      setCurrentQuery('')
    }
  }, [currentResponse, mode, currentQuery])

  // Listen for query submissions
  useEffect(() => {
    const handleQuerySubmit = (event: Event) => {
      const customEvent = event as CustomEvent
      const { query } = customEvent.detail
      setCurrentQuery(query)
    }

    window.addEventListener('query-submitted', handleQuerySubmit)
    
    return () => {
      window.removeEventListener('query-submitted', handleQuerySubmit)
    }
  }, [])

  // Listen for file upload and deep search events
  useEffect(() => {
    const handleFileUpload = async (event: Event) => {
      const customEvent = event as CustomEvent
      const { file, query } = customEvent.detail
      
      console.log('File uploaded:', file.name, 'Query:', query)
      
      // Show loading state
      setIsProcessing(true)
      setShowCanvas(true)
      setCanvasContent('') // Clear previous content
      setCanvasFileName(file.name)
      setDeepSearchResult(null) // Clear previous deep search
      
      // Simulate processing delay (in production, this would be actual API call)
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // Generate mock compliance report based on file
      const mockReport = generateMockComplianceReport(file.name, query)
      setCanvasContent(mockReport)
      setIsProcessing(false)
      
      // Announce to screen readers
      const announcement = `Compliance analysis complete for ${file.name}`
      const liveRegion = document.createElement('div')
      liveRegion.setAttribute('role', 'status')
      liveRegion.setAttribute('aria-live', 'polite')
      liveRegion.className = 'sr-only'
      liveRegion.textContent = announcement
      document.body.appendChild(liveRegion)
      setTimeout(() => document.body.removeChild(liveRegion), 1000)
    }

    // DEEP SEARCH EVENT HANDLER - This is where deep search results are processed
    const handleDeepSearchComplete = (event: Event) => {
      const customEvent = event as CustomEvent
      const { query, result, file } = customEvent.detail
      
      console.log('Deep search completed:', query, result)
      
      // Store deep search result for display
      setDeepSearchResult(result)
      
      if (mode === 'compliance') {
        // COMPLIANCE MODE: Show deep search results in canvas
        if (file) {
          setShowCanvas(true)
          setCanvasFileName(file.name)
          
          // Generate report if not already shown
          if (!canvasContent) {
            const mockReport = generateMockComplianceReport(file.name, query)
            setCanvasContent(mockReport)
          }
        }
      } else {
        // GENERAL MODE: Deep search results are handled by the RAG store
        // Messages are automatically added through the submitQuery flow
        console.log('Deep search completed in general mode:', result)
      }
    }

    window.addEventListener('file-uploaded', handleFileUpload)
    window.addEventListener('deep-search-complete', handleDeepSearchComplete)
    
    return () => {
      window.removeEventListener('file-uploaded', handleFileUpload)
      window.removeEventListener('deep-search-complete', handleDeepSearchComplete)
    }
  }, [mode, canvasContent])

  // Toggle canvas visibility
  const toggleCanvas = () => {
    setShowCanvas(!showCanvas)
  }

  // Handle retry for errors
  const handleRetry = () => {
    clearError()
    // Retry last query if available
    // This would need to be implemented with query history
  }

  // In compliance mode with canvas, show split view
  const isComplianceWithCanvas = mode === 'compliance' && showCanvas && canvasContent

  return (
    <div className="flex h-screen flex-col bg-slate-50">
      {/* Drag and Drop Overlay */}
      <DragDropOverlay onFileDrop={handleFileDrop} maxFiles={3} />
      
      <ChatHeader />
      
      <div className="flex flex-1 overflow-hidden">
        {/* Chat Area - 40% width in compliance mode with canvas, full width otherwise */}
        <div 
          className={`flex flex-col ${
            isComplianceWithCanvas ? 'w-full lg:w-[40%]' : 'w-full'
          } transition-all duration-300 overflow-hidden`}
        >
          <div className="flex w-full flex-1 flex-col overflow-hidden">
            <div className="mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8 flex-shrink-0">
            {/* RAG Loading State */}
            <AnimatePresence>
              {loading && mode === 'compliance' && (
                <motion.div 
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  transition={{ duration: 0.2 }}
                  className="mb-4 p-4 bg-white rounded-lg border border-slate-200 shadow-sm"
                >
                  <RAGProgress 
                    events={wsEvents} 
                    isComplete={false} 
                  />
                </motion.div>
              )}
            </AnimatePresence>
            
            {/* RAG Error State */}
            <AnimatePresence>
              {error && mode === 'compliance' && (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.2 }}
                  className="mb-4 p-4 bg-red-50 rounded-lg border border-red-200"
                >
                  <div className="flex items-start gap-2">
                    <AlertCircle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <p className="font-body text-sm text-red-800">{error}</p>
                      <Button
                        onClick={handleRetry}
                        variant="outline"
                        size="sm"
                        className="mt-2"
                      >
                        Retry
                      </Button>
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
            
            {loadingMessages ? (
              <div className="flex items-center justify-center py-12">
                <EnhancedLoading stage="searching" />
              </div>
            ) : null}
            </div>
            
            {/* Messages with scrollbar on far right OR Empty State */}
            {!loadingMessages && (
              <div className="flex-1 overflow-y-auto">
                {hasMessages ? (
                  <div className="mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8">
                    <ChatMessages messages={messages} />
                    
                    {/* Enhanced Typing Indicator */}
                    <AnimatePresence>
                      {(loading || isProcessing) && (
                        <div className="mt-4 flex justify-start">
                          <TypingIndicator />
                        </div>
                      )}
                    </AnimatePresence>
                  </div>
                ) : (
                  /* Empty State with Centered Input */
                  <motion.div 
                    className="flex flex-col h-full justify-center py-8"
                    initial={{ opacity: 1 }}
                    animate={{ opacity: isTransitioning ? 0 : 1 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="space-y-8">
                      {/* 1. Greeting and assistant text */}
                      <EmptyState onPromptSelect={handlePromptSelect} />
                      
                      {/* 2. Centered Input */}
                      <CenteredInput 
                        onSend={handleCenteredSend}
                        disabled={loading}
                        isTransitioning={isTransitioning}
                      />
                    </div>
                  </motion.div>
                )}
              </div>
            )}
          </div>
          {/* Only show ChatInput when there are messages */}
          {hasMessages && <ChatInput />}
        </div>

        {/* Canvas Toggle Button - Icon Only */}
        <AnimatePresence>
          {mode === 'compliance' && canvasContent && canvasFileName && (
            <motion.button
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.8 }}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.95 }}
              transition={{ duration: 0.2 }}
              onClick={toggleCanvas}
              className={cn(
                'fixed right-4 top-20 z-30 rounded-full bg-iris-600 p-2.5 text-white shadow-md transition-all hover:bg-iris-700 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-iris-500 focus-visible:ring-offset-2',
                showCanvas && 'lg:right-[calc(60%+1rem)]'
              )}
              aria-label={showCanvas ? 'Close compliance analysis' : 'Open compliance analysis'}
              title={showCanvas ? 'Close Analysis' : 'View Analysis'}
            >
              <AnimatePresence mode="wait">
                {showCanvas ? (
                  <motion.svg 
                    key="close"
                    initial={{ rotate: -90, opacity: 0 }}
                    animate={{ rotate: 0, opacity: 1 }}
                    exit={{ rotate: 90, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="h-4 w-4" 
                    fill="none" 
                    viewBox="0 0 24 24" 
                    stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </motion.svg>
                ) : (
                  <motion.div
                    key="open"
                    initial={{ rotate: -90, opacity: 0 }}
                    animate={{ rotate: 0, opacity: 1 }}
                    exit={{ rotate: 90, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <FileText className="h-4 w-4" />
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.button>
          )}
        </AnimatePresence>

        {/* Compliance Canvas - 60% width, only shown when there's content */}
        <AnimatePresence>
          {mode === 'compliance' && showCanvas && canvasContent && (
            <motion.div 
              initial={{ opacity: 0, x: 100 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 100 }}
              transition={{ duration: 0.3, ease: "easeOut" }}
              className="hidden lg:block lg:w-[60%] relative"
            >
              <ComplianceCanvas 
                content={canvasContent}
                fileName={canvasFileName}
                ragResponse={currentResponse || undefined}
                searchQueries={currentResponse?.search_queries_used}
                documentCount={currentResponse?.documents_found}
                deepSearchResult={deepSearchResult}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}