'use client'

import { useState, useEffect } from 'react'
import { ChatHeader } from '@/components/layout/chat-header'
import { ChatMessages } from './chat-messages'
import { ChatInput } from './chat-input'
import { ComplianceCanvas } from './compliance-canvas'
import { RAGProgress } from './rag-progress'
import { TypingIndicator } from './loading-indicator'
import { useChatModeStore } from '@/lib/store/chat-mode-store'
import { useRAGStore } from '@/lib/store/rag-store'
import { useAuthStore } from '@/lib/store/auth-store'
import type { Message } from '@/types'
import { AlertCircle, FileText } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'

interface ChatContainerProps {
  messages: Message[]
}

// Generate mock compliance report based on file
function generateMockComplianceReport(fileName: string, query: string): string {
  const timestamp = new Date().toLocaleDateString('en-PH', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
  
  // Different reports based on file name patterns
  if (fileName.toLowerCase().includes('disaster') || fileName.toLowerCase().includes('barangay') || fileName.toLowerCase().includes('plan')) {
    return `# Compliance Analysis Report

## ⚠️ AI-Generated Analysis Disclaimer
**This analysis is generated by AI and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified legal professionals, compliance officers, or government authorities. Always verify compliance requirements with official sources and seek professional legal counsel for critical decisions.**

---

**Document:** ${fileName}  
**Analysis Date:** ${timestamp}  
**Query:** ${query}

## Compliance Score: 75% ⚠️

### Overall Assessment
Your barangay disaster preparedness plan shows good foundational elements but requires several critical additions to fully comply with **RA 10121 (Philippine Disaster Risk Reduction and Management Act of 2010)** and related NDRRMC guidelines.

---

## ✅ Compliant Sections

### 1. Evacuation Plan (Section 3)
- **Status:** ✅ Compliant
- **Finding:** Evacuation centers, routes, and procedures are clearly documented
- **Reference:** RA 10121, Section 12 - Local DRRM Plans

### 2. BDRRMC Structure (Section 4.1)
- **Status:** ✅ Compliant  
- **Finding:** Committee structure follows NDRRMC guidelines with proper designation of roles
- **Reference:** NDRRMC Memorandum Circular No. 4, Series of 2012

### 3. Relief Operations (Section 5)
- **Status:** ✅ Compliant
- **Finding:** Relief goods inventory and distribution plan documented
- **Reference:** RA 10121, Section 13 - Relief and Recovery

---

## ⚠️ Sections Needing Minor Revisions

### 1. Communication System (Section 7)
- **Issue:** Missing social media monitoring and fake news protocols
- **Recommendation:** Add procedures for verifying and countering misinformation during disasters
- **Reference:** NDRRMC Guidelines on Information Management

### 2. Budget Allocation (Section 8)
- **Issue:** No breakdown for Quick Response Fund (QRF) as mandated
- **Recommendation:** Allocate at least 30% of total DRRM budget to QRF
- **Reference:** RA 10121, Section 21 - Local DRRM Fund

---

## 🚫 Critical Missing Sections

### 1. Risk Assessment and Hazard Mapping
- **Status:** 🚫 Missing
- **Requirement:** Detailed hazard maps showing flood-prone areas, fault lines, and fire-risk zones
- **Impact:** Cannot effectively plan evacuation routes without proper risk assessment
- **Action Required:** Conduct barangay-level hazard mapping with PHIVOLCS and PAGASA data
- **Reference:** RA 10121, Section 12(b) - Risk Assessment

### 2. Community Training Plan
- **Status:** 🚫 Missing  
- **Requirement:** Scheduled training programs for residents on disaster preparedness
- **Impact:** Community may not know proper response procedures during actual disasters
- **Action Required:** 
  - Quarterly community disaster awareness seminars
  - Annual earthquake and fire drills with community participation
  - First aid training for at least 10% of households
- **Reference:** NDRRMC Memorandum Circular No. 5, Series of 2013

### 3. Risk Communication Strategy
- **Status:** 🚫 Missing
- **Requirement:** Clear protocols for warning dissemination and public information
- **Impact:** Delayed or unclear warnings can lead to casualties
- **Action Required:**
  - Multi-channel warning system (sirens, SMS, social media, radio)
  - Pre-scripted emergency messages in Filipino and English
  - Designated information officers
- **Reference:** RA 10121, Section 11 - Information Dissemination

### 4. Post-Disaster Recovery Plan
- **Status:** 🚫 Missing
- **Requirement:** Plans for rehabilitation and reconstruction after disasters
- **Impact:** Slow recovery and potential for recurring vulnerabilities
- **Action Required:**
  - Livelihood restoration programs
  - Psychosocial support services
  - Build-back-better guidelines
- **Reference:** RA 10121, Section 13 - Recovery and Rehabilitation

### 5. Vulnerable Groups Protection
- **Status:** 🚫 Partially Addressed
- **Requirement:** Specific protocols for PWD, elderly, pregnant women, children, and indigenous peoples
- **Impact:** Vulnerable groups may be overlooked during evacuation and relief
- **Action Required:**
  - Database of vulnerable individuals per purok
  - Buddy system for PWD and elderly
  - Special relief packs for infants and medical needs
- **Reference:** RA 10121, Section 16 - Vulnerable and Marginalized Groups

---

## 📋 Recommended Next Steps

### Immediate (Within 1 Month)
1. ✏️ Add Risk Assessment and Hazard Mapping section
2. ✏️ Develop Community Training Plan with schedule
3. ✏️ Create Risk Communication Strategy
4. ✏️ Update Budget to include QRF breakdown

### Short-term (Within 3 Months)
1. 📅 Conduct barangay-wide hazard mapping exercise
2. 📅 Schedule first community disaster preparedness seminar
3. 📅 Establish vulnerable groups database
4. 📅 Conduct table-top exercise with BDRRMC

### Long-term (Within 6 Months)
1. 🎯 Complete Post-Disaster Recovery Plan
2. 🎯 Conduct full-scale disaster drill with community
3. 🎯 Establish partnerships with NGOs for disaster response
4. 🎯 Submit updated plan to City DRRM Office for validation

---

## 📚 Key Legal References

1. **Republic Act No. 10121** - Philippine Disaster Risk Reduction and Management Act of 2010
2. **NDRRMC Memorandum Circular No. 4, Series of 2012** - Guidelines on the Establishment of BDRRMC
3. **NDRRMC Memorandum Circular No. 5, Series of 2013** - Minimum Standards for Community-Based DRRM
4. **RA 10121 IRR** - Implementing Rules and Regulations

---

## ⚖️ Legal Disclaimer

**This AI-generated analysis is provided for informational and educational purposes only. It is not a substitute for:**
- Professional legal advice from licensed attorneys
- Official compliance audits by government agencies
- Consultation with certified disaster risk reduction experts
- Formal validation by the City/Municipal DRRM Office

**Users are strongly advised to:**
- Verify all findings with official government sources
- Consult with legal counsel before making compliance decisions
- Submit plans to proper authorities for official review
- Seek guidance from NDRRMC, OCD, or local DRRM offices

**Limitation of Liability:** The creators and operators of this AI tool assume no liability for decisions made based on this analysis. Users bear full responsibility for ensuring compliance with all applicable laws and regulations.

---

*Generated by LexInsights AI Compliance Assistant*  
*This is an automated analysis. Human review recommended.*`
  }
  
  // Default compliance report for other documents
  return `# Compliance Analysis Report

## ⚠️ AI-Generated Analysis Disclaimer
**This analysis is generated by AI and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified legal professionals, compliance officers, or government authorities. Always verify compliance requirements with official sources and seek professional legal counsel for critical decisions.**

---

**Document:** ${fileName}  
**Analysis Date:** ${timestamp}  
**Query:** ${query}

## Compliance Score: Analyzing...

### Document Processing
Your document is being analyzed for compliance with relevant Philippine laws and regulations. This may take a few moments.

### What We're Checking:
- Applicable laws and regulations
- Required sections and documentation
- Compliance gaps and risks
- Recommendations for improvement

---

## ⚖️ Legal Disclaimer

**This AI-generated analysis is provided for informational and educational purposes only. It is not a substitute for:**
- Professional legal advice from licensed attorneys
- Official compliance audits by government agencies  
- Consultation with certified compliance experts
- Formal validation by relevant government offices

**Users are strongly advised to:**
- Verify all findings with official government sources
- Consult with legal counsel before making compliance decisions
- Submit documents to proper authorities for official review
- Seek guidance from relevant regulatory agencies

---

*Generated by LexInsights AI Compliance Assistant*  
*This is an automated analysis. Human review recommended.*`
}

// Sample compliance report for demo
const sampleComplianceReport = `# Compliance Analysis Report

## Document Summary
**File:** sample-document.pdf  
**Analysis Date:** ${new Date().toLocaleDateString()}  
**Status:** ✅ Compliant

## Key Findings

### 1. Data Privacy Compliance
- **Status:** Compliant with Data Privacy Act of 2012
- **Requirements Met:**
  - Personal data collection procedures documented
  - Consent mechanisms in place
  - Data retention policies defined

### 2. Labor Code Requirements
- **Status:** Partially Compliant
- **Action Items:**
  - Update employee handbook to include remote work policies
  - Review overtime compensation structure
  - Implement mandatory rest day tracking

### 3. Tax Compliance
- **Status:** Compliant
- **Requirements Met:**
  - BIR registration current
  - Withholding tax procedures documented
  - VAT compliance verified

## Recommendations

1. **Immediate Actions**
   - Update employee handbook within 30 days
   - Schedule labor compliance training for HR team

2. **Long-term Improvements**
   - Implement automated compliance monitoring system
   - Quarterly compliance audits recommended

## Risk Assessment

| Area | Risk Level | Priority |
|------|-----------|----------|
| Data Privacy | Low | Medium |
| Labor Code | Medium | High |
| Tax Compliance | Low | Low |

## Next Steps

1. Review and implement recommended changes
2. Schedule follow-up compliance check in 90 days
3. Maintain documentation of all compliance activities

---
*This is a sample compliance report generated for demonstration purposes.*
`

export function ChatContainer({ messages }: ChatContainerProps) {
  const { mode } = useChatModeStore()
  const { user } = useAuthStore()
  const { 
    currentResponse, 
    loading, 
    error, 
    wsEvents, 
    submitQuery, 
    clearError 
  } = useRAGStore()
  
  const [showCanvas, setShowCanvas] = useState(false)
  const [canvasContent, setCanvasContent] = useState('')
  const [canvasFileName, setCanvasFileName] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)

  // Show canvas when we have a RAG response
  useEffect(() => {
    if (mode === 'compliance' && currentResponse) {
      setShowCanvas(true)
      setCanvasContent(currentResponse.summary)
      setCanvasFileName('rag-analysis')
    } else if (mode !== 'compliance') {
      setShowCanvas(false)
      setCanvasContent('')
      setCanvasFileName('')
    }
    // Don't auto-show canvas in compliance mode - wait for file upload
  }, [mode, currentResponse])

  // Listen for file upload events
  useEffect(() => {
    const handleFileUpload = async (event: CustomEvent) => {
      const { file, query } = event.detail
      
      console.log('File uploaded:', file.name, 'Query:', query)
      
      // Show loading state
      setIsProcessing(true)
      setShowCanvas(true)
      setCanvasContent('') // Clear previous content
      setCanvasFileName(file.name)
      
      // Simulate processing delay (in production, this would be actual API call)
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // Generate mock compliance report based on file
      const mockReport = generateMockComplianceReport(file.name, query)
      setCanvasContent(mockReport)
      setIsProcessing(false)
      
      // Announce to screen readers
      const announcement = `Compliance analysis complete for ${file.name}`
      const liveRegion = document.createElement('div')
      liveRegion.setAttribute('role', 'status')
      liveRegion.setAttribute('aria-live', 'polite')
      liveRegion.className = 'sr-only'
      liveRegion.textContent = announcement
      document.body.appendChild(liveRegion)
      setTimeout(() => document.body.removeChild(liveRegion), 1000)
    }

    window.addEventListener('file-uploaded', handleFileUpload as EventListener)
    
    return () => {
      window.removeEventListener('file-uploaded', handleFileUpload as EventListener)
    }
  }, [])

  // Toggle canvas visibility
  const toggleCanvas = () => {
    setShowCanvas(!showCanvas)
  }

  // Handle retry for errors
  const handleRetry = () => {
    clearError()
    // Retry last query if available
    // This would need to be implemented with query history
  }

  // In compliance mode with canvas, show split view
  const isComplianceWithCanvas = mode === 'compliance' && showCanvas && canvasContent

  return (
    <div className="flex h-screen flex-col bg-slate-50">
      <ChatHeader />
      
      <div className="flex flex-1 overflow-hidden">
        {/* Chat Area - 40% width in compliance mode with canvas, full width otherwise */}
        <div 
          className={`flex flex-col ${
            isComplianceWithCanvas ? 'w-full lg:w-[40%]' : 'w-full'
          } transition-all duration-300`}
        >
          <div className="mx-auto flex w-full max-w-3xl flex-1 flex-col overflow-hidden px-2 sm:px-4">
            {/* RAG Loading State */}
            {loading && mode === 'compliance' && (
              <div className="mb-4 p-4 bg-white rounded-lg border border-slate-200 shadow-sm">
                <RAGProgress 
                  events={wsEvents} 
                  isComplete={false} 
                />
              </div>
            )}
            
            {/* RAG Error State */}
            {error && mode === 'compliance' && (
              <div className="mb-4 p-4 bg-red-50 rounded-lg border border-red-200">
                <div className="flex items-start gap-2">
                  <AlertCircle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
                  <div className="flex-1">
                    <p className="font-body text-sm text-red-800">{error}</p>
                    <Button
                      onClick={handleRetry}
                      variant="outline"
                      size="sm"
                      className="mt-2"
                    >
                      Retry
                    </Button>
                  </div>
                </div>
              </div>
            )}
            
            <ChatMessages messages={messages} />
            
            {/* Typing Indicator */}
            {(loading || isProcessing) && (
              <div className="mt-4 flex justify-start">
                <TypingIndicator />
              </div>
            )}
          </div>
          <ChatInput />
        </div>

        {/* Canvas Toggle Button - Icon Only */}
        {mode === 'compliance' && canvasContent && canvasFileName && (
          <button
            onClick={toggleCanvas}
            className={cn(
              'fixed right-4 top-20 z-30 rounded-full bg-iris-600 p-2.5 text-white shadow-md transition-all hover:bg-iris-700 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-iris-500 focus-visible:ring-offset-2',
              showCanvas && 'lg:right-[calc(60%+1rem)]'
            )}
            aria-label={showCanvas ? 'Close compliance analysis' : 'Open compliance analysis'}
            title={showCanvas ? 'Close Analysis' : 'View Analysis'}
          >
            {showCanvas ? (
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            ) : (
              <FileText className="h-4 w-4" />
            )}
          </button>
        )}

        {/* Compliance Canvas - 60% width, only shown when there's content */}
        {mode === 'compliance' && showCanvas && canvasContent && (
          <div className="hidden lg:block lg:w-[60%] relative">
            <ComplianceCanvas 
              content={canvasContent}
              fileName={canvasFileName}
              ragResponse={currentResponse || undefined}
              searchQueries={currentResponse?.search_queries_used}
              documentCount={currentResponse?.documents_found}
            />
          </div>
        )}
      </div>
    </div>
  )
}
